# if you do like this then multiple applicaotin can use these env variables
apiVersion: v1 
kind: ConfigMap
metadata:
  name: ecom-backend-config
data:
  # 1st tyeps of secrates
  database_url: "mysql://ecom-db:3306/shop"
  cache_size: "1000"
  payment_gateway_url: "https://payment-gateway.example.com"
  max_cart_items: "50"
  session_timeout: "3600"

  # 2nd tyeps of secrates
  # file-like keys if i want to create .env file eventually then so in your final pod where your app is there it will create .env file there
  application.properties: | # i want this to reach as file in my final pod
    app.name=ecom-backend
    app.environment-production logging.level=INFO
    max.connections=100
  database.properties: |
    db.driverClassName=com.mysql.cj.jdbc.Driver
    db.username=ecom_user
    db.password-securepassword
    db.maxPoolSize=20
  cache.properties: |
    cache.type=redis
    cache.host=redis-cache
    cache.port=6379
    cache.ttl=600
  payment.properties: |
    gateway.url=https://payment-gateway.example.com
    gateway.apiKey-your_api_key_here
    gateway.timeout=30


