# if you do like this then multiple applicaotin can use these env variables
apiVersion: v1 
kind: ConfigMap
metadata:
  name: ecom-backend-config
data:
  # 1st tyeps of secrates
  database_url: "mysql://ecom-db:3306/shop"
  cache_size: "1000"
  payment_gateway_url: "https://payment-gateway.example.com"
  max_cart_items: "50"
  session_timeout: "3600"

  # 2nd tyeps of secrates
  # file-like keys if i want to create .env file eventually then so in your final pod where your app is there it will create .env file there
  application.properties: | # i want this to reach as file in my final pod
    app.name=ecom-backend
    app.environment-production logging.level=INFO
    max.connections=100
  database.properties: |
    db.driverClassName=com.mysql.cj.jdbc.Driver
    db.username=ecom_user
    db.password-securepassword
    db.maxPoolSize=20
  cache.properties: |
    cache.type=redis
    cache.host=redis-cache
    cache.port=6379
    cache.ttl=600
  payment.properties: |
    gateway.url=https://payment-gateway.example.com
    gateway.apiKey-your_api_key_here
    gateway.timeout=30




apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL  # this values you get form 1st tyeps of secrates
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config 
              key: database_url
        - name: CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: cache_size
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: payment_gateway_url
        - name: MAX_CART_ITEMS
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: max_cart_items
        - name: SESSION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: session_timeout
        volumeMounts: #  # this values you get form 2nd tyeps of secrates
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:   # create a voume which pick all the configration from this config map which we created above ecom-backend-config 
      - name: config-volume
        configMap:
          name: ecom-backend-config