

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL  # this values you get form 1st tyeps of secrates
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config 
              key: database_url
        - name: CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: cache_size
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: payment_gateway_url
        - name: MAX_CART_ITEMS
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: max_cart_items
        - name: SESSION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: ecom-backend-config
              key: session_timeout
        volumeMounts: #  # this values you get form 2nd tyeps of secrates // see image 18
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:   # create a voume which pick all the configration from this config map which we created above ecom-backend-config 
      - name: config-volume
        configMap:
          name: ecom-backend-config